---
milestones:
  - 'R2 (v3.0.0)'
  - 'R3 (v4.0.0)'
  - 'R4 (v5.0.0)'
  - 'R5 (v6.0.0)'
  - 'R6 (v7.0.0)'
  - 'R7 (v8.0.0)'

labels:
  - name: bug
    description: "Something isn't working"
    color: "d73a4a"
  - name: documentation
    description: "Improvements or additions to documentation"
    color: "0075ca"
  - name: duplicate
    description: "This issue or pull request already exists"
    color: "cfd3d7"
  - name: enhancement
    description: "New feature or request"
    color: "a2eeef"
  - name: good first issue
    description: "Good for newcomers"
    color: "7057ff"
  - name: help wanted
    description: "Extra attention is needed"
    color: "008672"
  - name: invalid
    description: "This doesn't seem right"
    color: "e4e669"
  - name: question
    description: "Further information is requested"
    color: "d876e3"
  - name: support
    description: "Support request"
    color: "e99695"
  - name: wontfix
    description: "This will not be worked on"
    color: "ffffff"
  - name: on hold
    description: "Is on hold"
    color: "000000"
  - name: upstream
    description: "Implemented directly in the upstream"
    color: "0052cc"
  - name: housekeeping
    description: "Internal housekeeping"
    color: "d93f0b"
  - name: dependencies
    description: "Pull requests that update a dependency file"
    color: "0366d6"
  - name: security
    description: "Issues or pull requests that are security-relevant"
    color: "fc0000"
  - name: work in progress
    description: "Pull requests that are work in progress, do not merge them"
    color: "c5def5"
  - name: needs refinement
    description: "User stories that need to be refined for further progress"
    color: "8cb1fe"
  - name: IaaS
    description: "Issues or pull requests relevant for Team1: IaaS"
    color: "3d51e5"
  - name: Container
    description: "Issues or pull requests relevant for Team 2: Container Infra and Tooling"
    color: "0dce67"
  - name: Ops
    description: "Issues or pull requests relevant for Team 3: Ops Tooling"
    color: "f3de42"
  - name: Community
    description: "Issues or pull requests relevant for SIG Community"
    color: "26a69a"
  - name: IAM
    description: "Issues or pull requests relevant for SIG IAM"
    color: "7cb342"
  - name: osism
    description: "Issues or pull requests relevant for osism"
    color: "f4511e"
  - name: epic
    description: "Issues that are spread across multiple sprints"
    color: "6a5acd"
  - name: spike
    description: "Issues used to turn known-unknowns into known-knowns"
    color: "0366d6"
  - name: release3
    description: "Issues or pull requests that are aimed for release 3"
    color: "51e898"
  - name: action required
    description: "Issues or pull requests that urgently require action"
    color: "dc143c"
  - name: regression
    description: "Issues or pull requests that address a regression"
    color: "ffd700"
  - name: longterm
    description: "Issues or pull requests that relevent for longterm support"
    color: "ff00ff"
  - name: stale
    description: ""
    color: "774527"
  - name: e2e-test
    description: ""
    color: "1D76DB"
  - name: e2e-quick-test
    description: ""
    color: "1D76DB"
  - name: cancelled-e2e-test
    description: ""
    color: "BCD3CB"
  - name: cancelled-e2e-quick-test
    description: ""
    color: "BCD3CB"
  - name: failed-e2e-test
    description: ""
    color: "B60205"
  - name: failed-e2e-quick-test
    description: ""
    color: "B60205"
  - name: successful-e2e-test
    description: ""
    color: "59B40E"
  - name: successful-e2e-quick-test
    description: ""
    color: "59B40E"
  - name: standards
    description: "Issues / ADR / pull requests relevant for standardization & certification"
    color: "50c3a5"
  - name: "SCS enables"
    description: "SCS enables Operators, Integrators, Developers as well as Users"
    color: "D4C5F9"
  - name: "SCS is continuously built and tested"
    description: "SCS is continuously built and tested in order to raise velocity and quality"
    color: "D4C5F9"
  - name: "SCS is federated"
    description: "SCS is federated"
    color: "D4C5F9"
  - name: "SCS is standardized"
    description: "SCS is standardized"
    color: "D4C5F9"
  - name: "SCS is understandable"
    description: "SCS is understandable"
    color: "D4C5F9"
  - name: "SCS is opinionated"
    description: "SCS has the courage to take decisions in its implementation choices to provide a clear focus"
    color: "D4C5F9"
  - name: "SCS is transparent"
    description: "SCS is transparent"
    color: "D4C5F9"
  - name: "SCS-VP01"
    description: "Related to tender lot SCS-VP01"
    color: "0F5FE1"
  - name: "SCS-VP02"
    description: "Related to tender lot SCS-VP02"
    color: "0F5FE1"
  - name: "SCS-VP03"
    description: "Related to tender lot SCS-VP03"
    color: "0F5FE1"
  - name: "SCS-VP04"
    description: "Related to tender lot SCS-VP04"
    color: "0F5FE1"
  - name: "SCS-VP05"
    description: "Related to tender lot SCS-VP05"
    color: "0F5FE1"
  - name: "SCS-VP06a"
    description: "Related to tender lot SCS-VP06a"
    color: "0F5FE1"
  - name: "SCS-VP06b"
    description: "Related to tender lot SCS-VP06b"
    color: "0F5FE1"
  - name: "SCS-VP06c"
    description: "Related to tender lot SCS-VP06c"
    color: "0F5FE1"
  - name: "SCS-VP06d"
    description: "Related to tender lot SCS-VP06d"
    color: "0F5FE1"
  - name: "SCS-VP06e"
    description: "Related to tender lot SCS-VP06e"
    color: "0F5FE1"
  - name: "SCS-VP08"
    description: "Related to tender lot SCS-VP08"
    color: "0F5FE1"
  - name: "SCS-VP09a"
    description: "Related to tender lot SCS-VP09a"
    color: "0F5FE1"
  - name: "SCS-VP09b"
    description: "Related to tender lot SCS-VP09b"
    color: "0F5FE1"
  - name: "SCS-VP09c"
    description: "Related to tender lot SCS-VP09c"
    color: "0F5FE1"
  - name: "SCS-VP10"
    description: "Related to tender lot SCS-VP10"
    color: "0F5FE1"
  - name: "SCS-VP11"
    description: "Related to tender lot SCS-VP11"
    color: "0F5FE1"
  - name: "SCS-VP13"
    description: "Related to tender lot SCS-VP13"
    color: "0F5FE1"
  - name: "release-notes"
    description: "This change needs to be highlighted in the upcoming release notes"
    color: "50C3A5"
  # Sprint names
  - name: "Sprint Amsterdam"
    description: "Sprint Amsterdam (2023, cwk 16+17)"
    color: "4080c0"
  - name: "Sprint Bratislava"
    description: "Sprint Bratislava (2023, cwk 18+19)"
    color: "4080c0"
  - name: "Sprint Copenhagen"
    description: "Sprint Copenhagen (2023, cwk 20+21)"
    color: "4080c0"
  - name: "Sprint Dublin"
    description: "Sprint Dublin (2023, cwk 22+23)"
    color: "4080c0"
  - name: "Sprint Edmonton"
    description: "Sprint Edmonton (2023, cwk 24+25)"
    color: "4080c0"
  - name: "Sprint Freiburg"
    description: "Sprint Freiburg (2023, cwk 26+27)"
    color: "4080c0"
  - name: "Sprint Gothenburg"
    description: "Sprint Gothenburg (2023, cwk 28+29)"
    color: "4080c0"
  - name: "Sprint Hobart"
    description: "Sprint Hobart (2023, cwk 30+31)"
    color: "4080c0"
  - name: "Sprint Izmir"
    description: "Sprint Izmir (2023, cwk 32+33)"
    color: "4080c0"
  - name: "Sprint Jena"
    description: "Sprint Jena (2023, cwk 34+35)"
    color: "4080c0"
  - name: "Sprint Kyoto"
    description: "Sprint Kyoto (2023, cwk 36+37)"
    color: "4080c0"
  - name: "Sprint Ljubljana"
    description: "Sprint Ljubljana (2023, cwk 38+39)"
    color: "4080c0"
  - name: "Sprint Montreal"
    description: "Sprint Montreal (2023, cwk 40+41)"
    color: "4080c0"
  - name: "Sprint Nantes"
    description: "Sprint Nantes (2023, cwk 42+43)"
    color: "4080c0"
  - name: "Sprint Orlando"
    description: "Sprint Orlando (2023, cwk 44+45)"
    color: "4080c0"
  - name: "Sprint Poznan"
    description: "Sprint Poznan (2023, cwk 46+47)"
    color: "4080c0"
  - name: "Sprint Quito"
    description: "Sprint Quito (2023, cwk 48+49)"
    color: "4080c0"
  - name: "Sprint Reykjavik"
    description: "Sprint Reykjavik (2023, cwk 50+51)"
    color: "4080c0"
  - name: "Sprint Swindon"
    description: "Sprint Swindon (2023, cwk 52 + 2024, cwk 01)"
    color: "4080c0"
  - name: "Sprint Taipei"
    description: "Sprint Taipei (2024, cwk 02+03)"
    color: "4080c0"
  - name: "Sprint Utrecht"
    description: "Sprint Utrecht (2024, cwk 04+05)"
    color: "4080c0"
  - name: "Sprint Vancouver"
    description: "Sprint Vancouver (2024, cwk 06+07)"
    color: "4080c0"
  - name: "Sprint Wellington"
    description: "Sprint Wellington (2024, cwk 08+09)"
    color: "4080c0"
  - name: "Sprint Xalapa"
    description: "Sprint Xalapa (2024, cwk 10+11)"
    color: "4080c0"
  - name: "Sprint Ystad"
    description: "Sprint Ystad (2024, cwk 12+13)"
    color: "4080c0"
  - name: "Sprint Zaragoza"
    description: "Sprint Zaragoza (2024, cwk 14+15)"
    color: "4080c0"
