---
- hosts: localhost

  vars:
    gitstyring_root_dir: .

  tasks:
    - name: manage people
      opentelekomcloud.gitcontrol.members:
        root: "{{ gitstyring_root_dir }}"
        token: "{{ github_token }}"
      no_log: false

    - name: manage teams
      opentelekomcloud.gitcontrol.teams:
        root: "{{ gitstyring_root_dir }}"
        token: "{{ github_token }}"
      no_log: false

    - name: manage repositories
      opentelekomcloud.gitcontrol.repositories:
        root: "{{ gitstyring_root_dir }}"
        token: "{{ github_token }}"
      no_log: false
