---
system-config:
  default_branch: main
  description: The configuration of our SCS infrastructure
  homepage: 'https://scs.community/contribute/'
  archived: false
  has_issues: true
  has_projects: false
  has_wiki: false
  private: false
  delete_branch_on_merge: true
  allow_merge_commit: false
  allow_squash_merge: true
  allow_rebase_merge: true
  teams: []
  branch_protections:
    - branch: "main"
      template: "main"
