---
zuul_config:
  default_branch: main
  description: Zuul Config Files
  homepage: 'http://zuul.scs.community:9000/'
  topics:
    - zuul
  archived: false
  has_issues: true
  has_projects: false
  has_wiki: false
  private: false
  delete_branch_on_merge: true
  allow_merge_commit: false
  allow_squash_merge: true
  allow_rebase_merge: true
  teams: []
  collaborators: []
  branch_protections:
    - branch: "main"
      template: "main"
